### PR TITLE
final and tested version of loader

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Sorry, this contains ways too many new files and doesn't do what it says on the tin. You accidentally committed some linda stuff...

**Comment by Jailander** [comment]
It wasn't an accident, I left it there as I said in gitter to use as example until I write the readme which was my plan for today, but ... it is now my plan for tomorrow.

What do you mean with the first part, if its about this package not being adequate, it has always been here and I think somehow this is hardware related, but you are right maybe we should created a strands launch package. What do you think?

**Comment by marc-hanheide** [comment]
No, I meant the pull request contained too many files for just saying "final and tested version of loader". That's want to I meant with the proverb "what it says on the tin"... nevermind. I'm still not convinced that more launch files with the name Linda will help here... I really suggest to put it in the README if it's for documentation purposes.

There's nothing wrong with the package, at least not for now.

**Comment by Jailander** [comment]
Ok, now I get it, yes I'll create a readme and fix it now :)

**Comment by marc-hanheide** [comment]
looking at the files, the only Linda-specific bits are the arguments, right? The rest  would well be useful for others, wouldn't it? The arguments we would define in our `tmux` shell scripts anyway, wouldn't we? So, wouldn't those launch files not be incredible useful beyond the "Linda" scope if the specific args were taken out. Our aim has to be, that all sites run a small core set of files shared among the whole team with a few specific arguments. Plus very few extras that they need. 

So, my general suggestion is: We don't have robot specific-launch files. Instead, we have launch files which accept arguments to customise it for our robot. These args are _not_ set in the launch file, but are set in the `tmux` scripts (together with any specific env variables). Does that make sense, @hawesie, @cdondrup  ?
Plus, we might have an additional launch file for stuff people want to run specifically.

**Comment by Jailander** [comment]
Well the point of those launch files is precisely setting the arguments only, the thing is that setting it in command lines will result in extremely long commands, @cdondrup and I tought this way would be better when we set up the system like this in the integration camp.

However I do foresee a system on which there is only one file where all the parameters per robot are set and each launch file is launch according to this settings using your launch action server.

**Comment by marc-hanheide** [comment]
Ah... Clever!

**Pull request merged**
