### PR TITLE
Fixed disparity nodelet

### PR DESCRIPTION
**Pull request by RaresAmbrus**

### CODE REVIEW

**Comment by hawesie** [comment]
Does this still need merging?

**Comment by RaresAmbrus** [comment]
Yes, I haven't merged it yet. Was waiting for @ToMadoRe to check it out, I think he needed it for something.

**Comment by ToMadoRe** [comment]
We haven't tried it because we are using @nilsbore's cliff detection now instead of the disparity based one from another project. As we don't see any reason to change it, we don't need the disparity nodelet any more.

**Comment by RaresAmbrus** [comment]
@hawesie I think you can merge this, it doesn't really affect the rest of the openni pipeline, and we might want to use the disparity later on.

**Pull request merged**
