### PR TITLE
organizing launch files

### PR DESCRIPTION
**Pull request by bfalacerda**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
To be honest, I lost track with the discussion around monitored nav. If you guys tell me this is needed I'll merge it ...

**Comment by bfalacerda** [comment]
i think this structure makes sense, @cdondrup @Jailander ?

**Comment by Jailander** [comment]
yes it looks fine

**Comment by cdondrup** [comment]
I'm not sure how well the dynamic restarting of things will work but I wouldn't put the strands_ui in the robot launch file. Speaking from experience the webserver needed occasional restarts due to all kinds of reasons (might be better now that reload is supported) and also mary sometimes fails if pulse acts up and needs to be restarted. That would mean, if the restart of single components doesn't work, we would have to restart the whole thing.
I'm also still not a big fan of having the cameras in the strands_robot launch file but that seems to be accepted by most of the people. Still they are more likely to fail (or not start properly) than the rest of the hardware, also speaking from experience, and should go in a dedicated camera launch file imho.

**Comment by Jailander** [comment]
Yes, you are right, I was thinking about it, and I was thinking that these launch files (strands_robot and strands_navigation) could be decomposed by modules when the launch action server is used, but for now I think it would be hell to have to start 10 or more launch files to have to run the whole system, but if we have to keep restarting strands_ui maybe it would make sense to separate it now, the cameras don't fail that much anymore so I wouldn't put them apart yet.

**Comment by cdondrup** [comment]
Agreed. 
But strands_ui should be somewhere else, maybe on its own.

**Comment by Jailander** [comment]
@BFALacerda can you do that?

**Comment by bfalacerda** [comment]
done

**Comment by cdondrup** [comment]
I'll merge this then.

**Pull request merged**
